#! /bin/bash -x

read -p " Enter the Date: " date
read -p " Enter the Month: " month

if (( $month  <= 6 & $date <=  20 ))
then
        echo "True"
elif (( ($month >= 3) & ($month  < 6 ) & ( $date<20) ))
then
        echo "True"
else
        echo "False"
fi
