#! /bin/bash -x
R1=$((RANDOM%(999)+100))
R2=$((RANDOM%(999)+100))
R3=$((RANDOM%(999)+100))
R4=$((RANDOM%(999)+100))
R5=$((RANDOM%(999)+100))

if [ $R1 -gt $R2 ] && [ $R1 -gt $R3 ] && [ $R1 -gt $R4 ] && [ $R1 -gt $R5 ]
then
        echo "$R1 is greater"
elif [ $R2 -gt $R3 ] && [ $R2 -gt $R4 ] && [ $R2 -gt $R5 ]
then
        echo "$R2 is greater"
elif [ $R3 -gt $R4] && [ $R3 -gt $R5 ]
then
        echo "$R3 is greater"
elif [ $R4 -gt $R5 ]
then
        echo "$R4 is greater"
else
        echo "$R5 is greater"
fi
